// Supabase Edge Function: draft
//
// Phase 3 "Studio" (SPEC.md §6, §5 button inventory). Generates the text body for any
// outbound artifact type — hello, nudge, thank_you, stay_in_touch, cover_letter, plus
// application_question (answers a poster-written free-text question passed in extra_context) — from the
// career record + relevant context (application/JD/contact/debriefs). Reads fw_profile
// first per the ceiling rule (principle #1) and follows the networking-outreach rules: one
// hook, one ask, tight length caps for messages; a fuller but still honest body for
// cover_letter. No hardcoded phrase templates — everything is generated by Claude from the
// record + context, per principle #4 (nothing candidate-specific baked into code).
//
// This function is stateless like `scorecard` — it returns { body } only. The client (per
// SPEC.md principle #2: drafts only, nothing auto-sent) inserts the fw_drafts row itself
// with status 'draft', shows it in the reusable DraftPanel for editing, and only the human
// clicking [Mark sent] ever flips status. This function never sends anything and never
// writes to the database.
//
// Model + secret handling mirror `scorecard`: fw_settings.models.draft falls back to
// models.default, falls back to 'claude-sonnet-5'. ANTHROPIC_API_KEY must be a Supabase
// secret, never hardcoded.

import { createClient } from "jsr:@supabase/supabase-js@2";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

type DraftType =
  | "hello"
  | "nudge"
  | "thank_you"
  | "stay_in_touch"
  | "cover_letter"
  | "application_question";

const LENGTH_GUIDANCE: Record<DraftType, string> = {
  hello: "A short LinkedIn-style opener, 3-5 sentences max. One hook (something specific and true about them or their work), one clear ask (e.g. a 15-minute chat).",
  nudge: "A brief, warm follow-up on a live application, 3-5 sentences max. One hook reconnecting to why they're a fit, one clear ask (status update or next step).",
  thank_you: "A short post-interview thank-you, 4-6 sentences max. Reference something specific from the actual conversation, reinforce fit, one small forward-looking ask or note.",
  stay_in_touch: "A brief check-in to a standing contact with no active role in play, 3-5 sentences max. One hook (genuine, specific), one light ask (stay on their radar, or a quick catch-up).",
  cover_letter: "A full but tight cover letter, 3-4 short paragraphs. Opens with the real hook connecting the candidate to this role, ties 1-2 career-record achievements directly to the JD's pain line, closes with a clear, confident ask to move forward.",
  application_question:
    "Answer the application question passed in the additional context, directly and specifically. Default to 1-2 tight paragraphs; if the question states its own length/format requirement, follow that instead. Answer in the candidate's first-person voice, grounded in real named things from the career record (products, metrics, iterations), never generic filler. If the record genuinely doesn't support an answer, say what IS supported rather than inventing.",
};

const DRAFT_TOOL = {
  name: "emit_draft",
  description: "Emit the plain-text draft body for this outbound message. Ready to copy and send as-is, or lightly edited by the human first.",
  input_schema: {
    type: "object",
    properties: {
      body: { type: "string" },
    },
    required: ["body"],
  },
};

export function resolveModel(settings: Record<string, unknown>, action: string): string {
  const models = (settings.models ?? {}) as Record<string, string>;
  return models[action] ?? models.default ?? "claude-sonnet-5";
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: CORS_HEADERS });
  }

  try {
    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) {
      return new Response(
        JSON.stringify({
          error:
            "Missing Supabase secret ANTHROPIC_API_KEY. Set it with `supabase secrets set ANTHROPIC_API_KEY=sk-ant-...` (or via the dashboard's Edge Function secrets panel), then retry.",
        }),
        { status: 500, headers: { ...CORS_HEADERS, "content-type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    const body = await req.json().catch(() => ({}));
    const {
      type,
      application_id,
      contact_id,
      extra_context,
    } = body as {
      type?: DraftType;
      application_id?: string;
      contact_id?: string;
      extra_context?: string;
    };

    if (!type || !(type in LENGTH_GUIDANCE)) {
      return new Response(
        JSON.stringify({ error: "Provide a valid type: hello, nudge, thank_you, stay_in_touch, cover_letter, application_question." }),
        { status: 400, headers: { ...CORS_HEADERS, "content-type": "application/json" } }
      );
    }
    if (type === "application_question" && !extra_context?.trim()) {
      return new Response(
        JSON.stringify({ error: "application_question requires extra_context: the question text to answer." }),
        { status: 400, headers: { ...CORS_HEADERS, "content-type": "application/json" } }
      );
    }
    if (!application_id && !contact_id) {
      return new Response(JSON.stringify({ error: "Provide application_id and/or contact_id." }), {
        status: 400,
        headers: { ...CORS_HEADERS, "content-type": "application/json" },
      });
    }

    const [{ data: profile }, { data: settingsRows }] = await Promise.all([
      supabase.from("fw_profile").select("*").limit(1).maybeSingle(),
      supabase.from("fw_settings").select("key, value"),
    ]);

    const settings: Record<string, unknown> = {};
    for (const row of (settingsRows ?? []) as { key: string; value: unknown }[]) {
      settings[row.key] = row.value;
    }
    const model = resolveModel(settings, "draft");
    const profileRow = (profile ?? {}) as Record<string, unknown>;

    let application: Record<string, unknown> | null = null;
    let jd: Record<string, unknown> | null = null;
    let events: Record<string, unknown>[] = [];
    let prepDocs: Record<string, unknown>[] = [];
    let contact: Record<string, unknown> | null = null;

    if (application_id) {
      const [{ data: appRow }, { data: jdRows }, { data: eventRows }, { data: prepRows }] = await Promise.all([
        supabase.from("fw_applications").select("*").eq("id", application_id).maybeSingle(),
        supabase
          .from("fw_jds")
          .select("*")
          .eq("application_id", application_id)
          .order("created_at", { ascending: false })
          .limit(1),
        supabase
          .from("fw_events")
          .select("*")
          .eq("application_id", application_id)
          .order("occurred_at", { ascending: false })
          .limit(10),
        supabase.from("fw_prep_docs").select("*").eq("application_id", application_id),
      ]);
      application = appRow ?? null;
      jd = (jdRows ?? [])[0] ?? null;
      events = eventRows ?? [];
      prepDocs = prepRows ?? [];
    }

    if (contact_id) {
      const { data: contactRow } = await supabase.from("fw_contacts").select("*").eq("id", contact_id).maybeSingle();
      contact = contactRow ?? null;
    }

    const systemPrompt = `You are drafting ${type === "application_question" ? "an answer to a job-application question" : "a networking/outreach message"} for Fieldwork, a job-search cockpit, following these fixed rules: ${type === "application_question" ? "answer the question asked, nothing else" : "one hook, one ask"}, no filler, no generic phrases like "I hope this finds you well". The candidate's career record is the ceiling — never claim anything beyond it, never suggest claiming anything in "do not claim", never mention anything in "never mention". This is a DRAFT ONLY: the human reviews, edits, and sends it manually, so write it as ready-to-send prose, not a template with placeholders.

Style rule, absolute: NEVER use em dashes (—) or double hyphens (--) anywhere in the output. Where you would reach for an em dash, restructure the sentence or use a period, comma, or colon instead. Plain hyphens inside compound words are fine.

Message type: ${type}. ${LENGTH_GUIDANCE[type]}

Candidate career record (markdown, the ceiling):
${String(profileRow.career_record ?? "(none on file)")}

Locked summary: ${String(profileRow.locked_summary ?? "(none on file)")}
Hooks (name -> reusable framing, use if genuinely relevant): ${JSON.stringify(profileRow.hooks ?? {})}
Do not claim: ${Array.isArray(profileRow.do_not_claim) ? (profileRow.do_not_claim as string[]).join(", ") : "(none)"}
Never mention: ${Array.isArray(profileRow.never_mention) ? (profileRow.never_mention as string[]).join(", ") : "(none)"}

${application ? `Application context: ${application.title ?? "(untitled)"} at ${application.company}, status ${application.status}.` : ""}
${jd ? `Job description pain line: ${jd.pain_line ?? "(none)"}\nJD gaps: ${Array.isArray(jd.gaps) ? (jd.gaps as unknown[]).join(", ") : "(none)"}` : ""}
${events.length ? `Recent timeline events: ${JSON.stringify(events)}` : ""}
${prepDocs.length ? `Prep docs / debriefs on file (use for specific, true details to reference in a thank-you): ${JSON.stringify(prepDocs)}` : ""}
${contact ? `Contact: ${contact.name}, ${contact.role_title ?? "role unknown"} at ${contact.company ?? "unknown company"}. Warmth: ${contact.warmth}. Context notes: ${contact.context ?? "(none)"}` : ""}
${extra_context ? `Additional context supplied by the user: ${extra_context}` : ""}

Call emit_draft with the finished body — do not respond in plain text.`;

    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model,
        max_tokens: 1500,
        system: systemPrompt,
        messages: [{ role: "user", content: `Write the ${type} draft now.` }],
        tools: [DRAFT_TOOL],
        tool_choice: { type: "tool", name: "emit_draft" },
      }),
    });

    if (!res.ok) {
      const detail = await res.text();
      throw new Error(`Claude API error (${res.status}): ${detail.slice(0, 500)}`);
    }

    const payload = await res.json();
    const toolUse = (payload.content ?? []).find((b: { type: string }) => b.type === "tool_use");
    if (!toolUse) {
      throw new Error("Claude did not return a draft.");
    }
    // Hard backstop for the no-em-dash style rule: convert any stragglers to plain
    // punctuation (em dashes read as commas in prose; double hyphens likewise).
    const draftBody = String((toolUse.input as { body?: string }).body ?? "")
      .replace(/\s*—\s*/g, ", ")
      .replace(/\s*--\s*/g, ", ");

    return new Response(JSON.stringify({ body: draftBody }), {
      headers: { ...CORS_HEADERS, "content-type": "application/json" },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Unknown error in draft." }),
      { status: 500, headers: { ...CORS_HEADERS, "content-type": "application/json" } }
    );
  }
});
