// Hand-written TypeScript types matching the live Supabase schema (`fw_` prefixed
// tables). Generated by reading
// `list_tables` output directly — keep in sync with real columns, not guesses.

// Type-only import — erased at compile time, so the resume.ts → types.ts
// circularity is harmless.
import type { ResumeContent } from './resume';

export type FwStatus =
  | 'to_apply'
  | 'applied'
  | 'phone_screen'
  | 'interviewing'
  | 'final_round'
  | 'offer'
  | 'accepted'
  | 'rejected'
  | 'withdrawn'
  | 'ghosted'
  | 'passed';

/** Scorecard grade for a role, best to worst. Ordered — index in this array is the rank,
 * which is also the Postgres enum's own ordering (see fw_grade in schema.sql). */
export const FW_GRADES = ['A+', 'A', 'B', 'C', 'D', 'F'] as const;

export type FwGrade = (typeof FW_GRADES)[number];

export type FwEventType =
  | 'applied'
  | 'screen'
  | 'round'
  | 'debrief'
  | 'rejection'
  | 'nudge'
  | 'thank_you'
  | 'note'
  | 'status_change'
  | 'offer';

export type FwDraftType =
  | 'hello'
  | 'nudge'
  | 'thank_you'
  | 'stay_in_touch'
  | 'cover_letter'
  | 'application_question';

export type FwDraftStatus = 'draft' | 'sent';

export interface FwProfile {
  id: string;
  career_record: string | null;
  locked_summary: string | null;
  hooks: Record<string, string>;
  comp_floor: number | null;
  target_band_strategy: string | null;
  remote_prefs: string | null;
  target_titles: string[];
  avoid_titles: string[];
  do_not_claim: string[];
  never_mention: string[];
  file_name_pattern: string | null;
  created_at: string;
  updated_at: string;
}

export interface FwSettings {
  key: string;
  value: unknown;
  updated_at: string;
}

export interface FwApplication {
  id: string;
  company: string;
  title: string | null;
  status: FwStatus;
  date_applied: string | null;
  grade: FwGrade | null;
  comp_posted: string | null;
  comp_min: number | null;
  comp_max: number | null;
  remote_type: string | null;
  source: string | null;
  next_action: string | null;
  next_action_due: string | null;
  resume_filename: string | null;
  /** Last built (post-edit) resume JSON — persisted so a past build can be viewed,
   * re-edited, and re-exported without regenerating. */
  resume_content: ResumeContent | null;
  cover_letter: boolean;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface FwJd {
  id: string;
  application_id: string | null;
  url: string | null;
  raw_text: string | null;
  pain_line: string | null;
  gaps: unknown[];
  live_checked_at: string | null;
  source: string | null;
  created_at: string;
}

export interface FwContact {
  id: string;
  name: string;
  company: string | null;
  role_title: string | null;
  context: string | null;
  email: string | null;
  phone: string | null;
  linkedin: string | null;
  application_id: string | null;
  last_touch: string | null;
  next_action: string | null;
  warmth: string;
  created_at: string;
  updated_at: string;
}

export interface FwEvent {
  id: string;
  application_id: string;
  type: FwEventType;
  /** Date the event was logged (YYYY-MM-DD). Past tense — "this happened". */
  occurred_at: string;
  /** ISO timestamp a screen/round/debrief is booked for. Null = not scheduled, or already
   * happened. A future value means it has NOT occurred yet: it must not trigger a thank-you,
   * but it does count as contact for ghost detection. */
  scheduled_at: string | null;
  body: string | null;
  created_at: string;
}

export type FwRunKind = 'scorecard' | 'daily_loop_paste' | 'daily_loop_source';

/** One scorecard / daily_loop invocation. See fw_intake_runs in schema.sql for why the
 * counts live here rather than being derived from fw_applications: only roles that get
 * filed or discarded reach the pipeline, so this is the only record of the denominator. */
export interface FwIntakeRun {
  id: string;
  kind: FwRunKind;
  ran_at: string;
  requested: number | null;
  searched_queries: string[];
  candidates: number;
  duplicates: number;
  expired: number;
  errors: number;
  scored: number;
  /** Grade histogram for the run, e.g. {"A": 2, "B": 5}. */
  grades: Partial<Record<FwGrade, number>>;
  model: string | null;
  created_at: string;
}

export type FwRunOutcome = 'graded' | 'duplicate' | 'expired' | 'error';

/** One role a run looked at, stored as the card itself. See fw_intake_run_items in
 * schema.sql: a scored card otherwise lives only in the HTTP response, so a failed render
 * burns the Claude call. Carries enough to re-file the role later without re-scoring. */
export interface FwIntakeRunItem {
  id: string;
  run_id: string;
  company: string;
  title: string | null;
  url: string | null;
  outcome: FwRunOutcome;
  grade: FwGrade | null;
  comp_min: number | null;
  comp_max: number | null;
  remote_type: string | null;
  location: string | null;
  pain_line: string | null;
  gaps: string[];
  reasoning: string | null;
  jd_text: string | null;
  live_checked_at: string | null;
  liveness_note: string | null;
  error: string | null;
  created_at: string;
}

export interface FwLesson {
  id: string;
  application_id: string | null;
  date: string | null;
  company: string | null;
  role: string | null;
  stage_reached: string | null;
  stated_reason: string | null;
  real_signal: string | null;
  adjustment: string | null;
  created_at: string;
}

export interface FwDraft {
  id: string;
  application_id: string | null;
  contact_id: string | null;
  type: FwDraftType;
  body: string;
  status: FwDraftStatus;
  sent_at: string | null;
  created_at: string;
}

export interface FwPrepDoc {
  id: string;
  application_id: string;
  round_type: string | null;
  content: string | null;
  debriefs: unknown[];
  created_at: string;
  updated_at: string;
}

// Minimal Database shape for the supabase-js generic client. Not a full
// generated schema — just enough structure for typed table access.
export interface Database {
  public: {
    Tables: {
      fw_profile: { Row: FwProfile; Insert: Partial<FwProfile>; Update: Partial<FwProfile> };
      fw_settings: { Row: FwSettings; Insert: Partial<FwSettings>; Update: Partial<FwSettings> };
      fw_applications: {
        Row: FwApplication;
        Insert: Partial<FwApplication>;
        Update: Partial<FwApplication>;
      };
      fw_jds: { Row: FwJd; Insert: Partial<FwJd>; Update: Partial<FwJd> };
      fw_contacts: { Row: FwContact; Insert: Partial<FwContact>; Update: Partial<FwContact> };
      fw_events: { Row: FwEvent; Insert: Partial<FwEvent>; Update: Partial<FwEvent> };
      fw_lessons: { Row: FwLesson; Insert: Partial<FwLesson>; Update: Partial<FwLesson> };
      fw_drafts: { Row: FwDraft; Insert: Partial<FwDraft>; Update: Partial<FwDraft> };
      fw_prep_docs: { Row: FwPrepDoc; Insert: Partial<FwPrepDoc>; Update: Partial<FwPrepDoc> };
      fw_intake_runs: {
        Row: FwIntakeRun;
        Insert: Partial<FwIntakeRun>;
        Update: Partial<FwIntakeRun>;
      };
      fw_intake_run_items: {
        Row: FwIntakeRunItem;
        Insert: Partial<FwIntakeRunItem>;
        Update: Partial<FwIntakeRunItem>;
      };
    };
    Functions: {
      /** Claims project ownership for the caller on first sign-in (see schema.sql
       *  RLS). Idempotent: returns the owning uid, and is a no-op once claimed. */
      fw_claim_owner: { Args: Record<string, never>; Returns: string };
    };
  };
}
